// Generated by CoffeeScript 1.8.0
(function() {
  var Promise;

  Promise = require('bluebird');

  return module.exports = function(stream) {
    var chunks;
    chunks = [];
    return new Promise(function(resolve, reject) {
      stream.on('data', function(chunk) {
        return chunks.push(chunk);
      });
      stream.on('error', function(err) {
        return reject(err);
      });
      return stream.on('end', function() {
        return resolve(Buffer.concat(chunks));
      });
    });
  };

}).call(this);
